# Generated by Django 5.0.14 on 2026-02-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('puntuacion', models.IntegerField(max_length=50)),
            ],
        ),
    ]
