# Generated by Django 5.0.14 on 2026-05-14 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseñas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('juego', 'autor'), name='una_resena_por_usuario_y_juego'),
        ),
    ]
