# Generated by Django 5.0.14 on 2026-03-02 08:07

import reseñas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseñas', '0002_juego_resena_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(upload_to=reseñas.models.upload_to),
        ),
    ]
