# Generated by Django 5.0.14 on 2026-02-25 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseñas', '0003_rename_post_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
